import type { Metadata } from "next";
import { Clause, GithubIssues, LegalPage } from "@/client/components/legalPage";

export const metadata: Metadata = {
  title: "Privacy Policy — Flybox",
  description: "Privacy policy for Flybox.",
};

export default function PrivacyPolicy() {
  return (
    <LegalPage title="Privacy Policy" updated="August 16, 2026">
      <p>Flybox values your privacy. This Privacy Policy explains what information we collect, how we use it, and your rights regarding that information.</p>

      <Clause heading="Information We Collect">
        <p>Flybox does not require an account, an API key, or any personal information to use the website.</p>
        <p>There is no analytics or tracking on this site. The only information tied to your use of it is:</p>
        <ul>
          <li>A salted, one-way hash of your IP address, stored with each run purely to enforce rate limits (see below)</li>
          <li>The map position and any river names you enter, stored with the run so it can be listed on the Recent runs page</li>
        </ul>
        <p>Standard server logs kept by our hosting provider are outside our control and subject to their policy.</p>
      </Clause>

      <Clause heading="API Keys">
        <p>
          Flybox supplies its own third-party API keys and never asks you for one. Those keys stay on our server and are never sent to your browser. Because we
          pay for them, runs are rate limited.
        </p>
      </Clause>

      <Clause heading="Output Files and the Public Catalog">
        <p>Files generated by Flybox are stored temporarily in our database and are automatically removed during routine cleanup.</p>
        <p>
          <strong>Recent runs are listed publicly.</strong> The Recent runs page shows the date and approximate location of the most recent runs and lets anyone
          download their output files. Runs are not tied to any account or identity, but do not use Flybox for a search you would not want listed. Only the
          location you chose, any river names you entered, and the resulting public business data appear there.
        </p>
      </Clause>

      <Clause heading="Business and Public Data">
        <p>Flybox collects and displays publicly available information about fly-fishing-related businesses.</p>
        <p>This may include:</p>
        <ul>
          <li>Business names and locations</li>
          <li>Contact information published on business websites</li>
          <li>Fishing reports or other public content</li>
          <li>Business metadata obtained via third-party services</li>
        </ul>
        <p>
          This information is sourced from publicly accessible websites and third-party APIs (such as SerpAPI). Flybox does not collect private or confidential
          information.
        </p>
      </Clause>

      <Clause heading="Use of Third-Party Services">
        <p>Flybox sends data to the following third parties in the course of a run:</p>
        <ul>
          <li>
            <strong>SerpAPI</strong> — receives the map position you chose, to search Google Maps for nearby shops.
          </li>
          <li>
            <strong>OpenAI</strong> — receives the text scraped from shop websites, to summarize it. Only that scraped text is sent; nothing about you is
            included.
          </li>
          <li>
            <strong>OpenStreetMap / Nominatim</strong> — receives coordinates, to turn them into a place name for the Recent runs page and to power the map
            search box.
          </li>
        </ul>
        <p>
          Each has its own privacy policy and terms. Flybox is not responsible for the privacy practices of third-party services or of the external websites it
          crawls.
        </p>
      </Clause>

      <Clause heading="Cookies and Local Storage">
        <p>
          Flybox sets no cookies and runs no analytics. It does use your browser&apos;s local storage to remember your theme preference, your last form
          settings, and the ID of a run in progress so you do not lose it on refresh. That data never leaves your browser and you can clear it at any time
          through your browser settings.
        </p>
      </Clause>

      <Clause heading="Data Accuracy and Updates">
        <p>
          Flybox does not guarantee that business information displayed on the site is accurate or up to date. Businesses are encouraged to verify information
          through their own official channels.
        </p>
      </Clause>

      <Clause heading="Data Removal Requests">
        <p>
          If you are a business owner and believe information displayed on Flybox is inaccurate or should be removed, you may contact us at the email below and
          requests will be evaluated on a case-by-case basis.
        </p>
      </Clause>

      <Clause heading="Personal Privacy">
        <p>
          Flybox has no accounts, no sign-in, and no advertising or analytics trackers. The only thing we store that relates to you personally is the salted
          hash of your IP address described above, which we keep solely to enforce rate limits and which is deleted along with the run.
        </p>
      </Clause>

      <Clause heading="Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated effective date. Continued use of the
          website after changes are posted constitutes acceptance of the updated policy.
        </p>
      </Clause>

      <Clause heading="Contact">
        <p>
          If you have questions about this Privacy Policy or Flybox&apos;s data practices, please open an issue on our <GithubIssues />.
        </p>
      </Clause>
    </LegalPage>
  );
}
