import type { Metadata } from "next";
import { Clause, GithubIssues, LegalPage } from "@/client/components/legalPage";

export const metadata: Metadata = {
  title: "Privacy Policy — Flybox",
  description: "Privacy policy for Flybox.",
};

export default function PrivacyPolicy() {
  return (
    <LegalPage title="Privacy Policy" updated="April 11, 2026">
      <p>Flybox values your privacy. This Privacy Policy explains what information we collect, how we use it, and your rights regarding that information.</p>

      <Clause heading="Information We Collect">
        <p>Flybox does not require an account, an API key, or any personal information to use the website.</p>
        <p>We may collect limited, non-identifying information automatically, such as:</p>
        <ul>
          <li>Browser type</li>
          <li>Device type</li>
          <li>General usage data (pages visited, approximate location)</li>
        </ul>
        <p>This information is used solely to understand site usage and improve the service.</p>
      </Clause>

      <Clause heading="API Keys">
        <p>
          Flybox encourages users to provide their own third-party API keys (such as SerpAPI and OpenAI) to stay in control of their usage limits and costs.
          When provided, these keys are used only to make requests on your behalf during your session and are never stored, logged, or retained by Flybox.
        </p>
      </Clause>

      <Clause heading="Output Files and Temporary Storage">
        <p>
          Files generated by Flybox (such as Excel reports) are stored temporarily in our database solely to facilitate your download. They are not shared with
          third parties and are automatically removed during routine cleanup.
        </p>
      </Clause>

      <Clause heading="Business and Public Data">
        <p>Flybox collects and displays publicly available information about fly-fishing-related businesses.</p>
        <p>This may include:</p>
        <ul>
          <li>Business names and locations</li>
          <li>Contact information published on business websites</li>
          <li>Fishing reports or other public content</li>
          <li>Business metadata obtained via third-party services</li>
        </ul>
        <p>
          This information is sourced from publicly accessible websites and third-party APIs (such as SerpAPI). Flybox does not collect private or confidential
          information.
        </p>
      </Clause>

      <Clause heading="Use of Third-Party Services">
        <p>
          Flybox relies on third-party tools and services to collect and display information. These services may have their own privacy policies and terms.
          Flybox is not responsible for the privacy practices of third-party services or external websites.
        </p>
      </Clause>

      <Clause heading="Cookies">
        <p>
          Flybox may use cookies or similar technologies to support basic site functionality and analytics. You can control or disable cookies through your
          browser settings.
        </p>
      </Clause>

      <Clause heading="Data Accuracy and Updates">
        <p>
          Flybox does not guarantee that business information displayed on the site is accurate or up to date. Businesses are encouraged to verify information
          through their own official channels.
        </p>
      </Clause>

      <Clause heading="Data Removal Requests">
        <p>
          If you are a business owner and believe information displayed on Flybox is inaccurate or should be removed, you may contact us at the email below and
          requests will be evaluated on a case-by-case basis.
        </p>
      </Clause>

      <Clause heading="Personal Privacy">
        <p>Flybox does not knowingly collect, store, or process any personal information from anyone.</p>
      </Clause>

      <Clause heading="Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated effective date. Continued use of the
          website after changes are posted constitutes acceptance of the updated policy.
        </p>
      </Clause>

      <Clause heading="Contact">
        <p>
          If you have questions about this Privacy Policy or Flybox&apos;s data practices, please open an issue on our <GithubIssues />.
        </p>
      </Clause>
    </LegalPage>
  );
}
